Vagrant::Config.run do |config|
    config.vm.box = "trusty64"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    config.vm.network :hostonly, "10.0.0.2"
    config.vm.host_name = "dig.local"
        
    config.vm.share_folder "www", "/vagrant", "../", 
        :owner => "www-data", :group => "www-data"
        
    config.vm.provision :shell, :path => "provision.sh"
end
